# These are supported funding model platforms

github: 
patreon: zwtdzh 
open_collective: zwtdzh 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
custom: https://www.paypal.me/zwtdzh
